// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: vst_bridge.proto

package main

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Echo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Echo) Reset() {
	*x = Echo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vst_bridge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_vst_bridge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_vst_bridge_proto_rawDescGZIP(), []int{0}
}

type Echo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *Echo_Request) Reset() {
	*x = Echo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vst_bridge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo_Request) ProtoMessage() {}

func (x *Echo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vst_bridge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo_Request.ProtoReflect.Descriptor instead.
func (*Echo_Request) Descriptor() ([]byte, []int) {
	return file_vst_bridge_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Echo_Request) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type Echo_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *Echo_Reply) Reset() {
	*x = Echo_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vst_bridge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo_Reply) ProtoMessage() {}

func (x *Echo_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_vst_bridge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo_Reply.ProtoReflect.Descriptor instead.
func (*Echo_Reply) Descriptor() ([]byte, []int) {
	return file_vst_bridge_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Echo_Reply) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

var File_vst_bridge_proto protoreflect.FileDescriptor

var file_vst_bridge_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x73, 0x74, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x22, 0x3e, 0x0a,
	0x04, 0x45, 0x63, 0x68, 0x6f, 0x1a, 0x1b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73,
	0x74, 0x72, 0x1a, 0x19, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x32, 0x45, 0x0a,
	0x09, 0x56, 0x53, 0x54, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x45, 0x63,
	0x68, 0x6f, 0x12, 0x17, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x45,
	0x63, 0x68, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x76, 0x73,
	0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vst_bridge_proto_rawDescOnce sync.Once
	file_vst_bridge_proto_rawDescData = file_vst_bridge_proto_rawDesc
)

func file_vst_bridge_proto_rawDescGZIP() []byte {
	file_vst_bridge_proto_rawDescOnce.Do(func() {
		file_vst_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_vst_bridge_proto_rawDescData)
	})
	return file_vst_bridge_proto_rawDescData
}

var file_vst_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vst_bridge_proto_goTypes = []interface{}{
	(*Echo)(nil),         // 0: vstbridge.Echo
	(*Echo_Request)(nil), // 1: vstbridge.Echo.Request
	(*Echo_Reply)(nil),   // 2: vstbridge.Echo.Reply
}
var file_vst_bridge_proto_depIdxs = []int32{
	1, // 0: vstbridge.VSTBridge.Echo:input_type -> vstbridge.Echo.Request
	2, // 1: vstbridge.VSTBridge.Echo:output_type -> vstbridge.Echo.Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vst_bridge_proto_init() }
func file_vst_bridge_proto_init() {
	if File_vst_bridge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vst_bridge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vst_bridge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vst_bridge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vst_bridge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vst_bridge_proto_goTypes,
		DependencyIndexes: file_vst_bridge_proto_depIdxs,
		MessageInfos:      file_vst_bridge_proto_msgTypes,
	}.Build()
	File_vst_bridge_proto = out.File
	file_vst_bridge_proto_rawDesc = nil
	file_vst_bridge_proto_goTypes = nil
	file_vst_bridge_proto_depIdxs = nil
}
