// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: vstbridge.proto

package vstbridge

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SetSampleRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetSampleRate) Reset() {
	*x = SetSampleRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSampleRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSampleRate) ProtoMessage() {}

func (x *SetSampleRate) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSampleRate.ProtoReflect.Descriptor instead.
func (*SetSampleRate) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{0}
}

type ProcessReplacing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessReplacing) Reset() {
	*x = ProcessReplacing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessReplacing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReplacing) ProtoMessage() {}

func (x *ProcessReplacing) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReplacing.ProtoReflect.Descriptor instead.
func (*ProcessReplacing) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{1}
}

type ProcessDoubleReplacing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessDoubleReplacing) Reset() {
	*x = ProcessDoubleReplacing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessDoubleReplacing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDoubleReplacing) ProtoMessage() {}

func (x *ProcessDoubleReplacing) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDoubleReplacing.ProtoReflect.Descriptor instead.
func (*ProcessDoubleReplacing) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{2}
}

type GetParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetParameter) Reset() {
	*x = GetParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameter) ProtoMessage() {}

func (x *GetParameter) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameter.ProtoReflect.Descriptor instead.
func (*GetParameter) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{3}
}

type SetParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetParameter) Reset() {
	*x = SetParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParameter) ProtoMessage() {}

func (x *SetParameter) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParameter.ProtoReflect.Descriptor instead.
func (*SetParameter) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{4}
}

type Echo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Echo) Reset() {
	*x = Echo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{5}
}

type FloatArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []float32 `protobuf:"fixed32,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *FloatArray) Reset() {
	*x = FloatArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatArray) ProtoMessage() {}

func (x *FloatArray) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatArray.ProtoReflect.Descriptor instead.
func (*FloatArray) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{6}
}

func (x *FloatArray) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type DoubleArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []float64 `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *DoubleArray) Reset() {
	*x = DoubleArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleArray) ProtoMessage() {}

func (x *DoubleArray) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleArray.ProtoReflect.Descriptor instead.
func (*DoubleArray) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{7}
}

func (x *DoubleArray) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetSampleRate_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SampleRate float32 `protobuf:"fixed32,2,opt,name=sampleRate,proto3" json:"sampleRate,omitempty"`
}

func (x *SetSampleRate_Request) Reset() {
	*x = SetSampleRate_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSampleRate_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSampleRate_Request) ProtoMessage() {}

func (x *SetSampleRate_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSampleRate_Request.ProtoReflect.Descriptor instead.
func (*SetSampleRate_Request) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SetSampleRate_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetSampleRate_Request) GetSampleRate() float32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type SetSampleRate_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetSampleRate_Reply) Reset() {
	*x = SetSampleRate_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSampleRate_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSampleRate_Reply) ProtoMessage() {}

func (x *SetSampleRate_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSampleRate_Reply.ProtoReflect.Descriptor instead.
func (*SetSampleRate_Reply) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{0, 1}
}

type ProcessReplacing_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Inputs       []*FloatArray `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	SampleFrames int32         `protobuf:"varint,3,opt,name=sampleFrames,proto3" json:"sampleFrames,omitempty"`
}

func (x *ProcessReplacing_Request) Reset() {
	*x = ProcessReplacing_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessReplacing_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReplacing_Request) ProtoMessage() {}

func (x *ProcessReplacing_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReplacing_Request.ProtoReflect.Descriptor instead.
func (*ProcessReplacing_Request) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ProcessReplacing_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProcessReplacing_Request) GetInputs() []*FloatArray {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ProcessReplacing_Request) GetSampleFrames() int32 {
	if x != nil {
		return x.SampleFrames
	}
	return 0
}

type ProcessReplacing_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outputs []*FloatArray `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (x *ProcessReplacing_Reply) Reset() {
	*x = ProcessReplacing_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessReplacing_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReplacing_Reply) ProtoMessage() {}

func (x *ProcessReplacing_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReplacing_Reply.ProtoReflect.Descriptor instead.
func (*ProcessReplacing_Reply) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ProcessReplacing_Reply) GetOutputs() []*FloatArray {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type ProcessDoubleReplacing_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Inputs       []*DoubleArray `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	SampleFrames int32          `protobuf:"varint,3,opt,name=sampleFrames,proto3" json:"sampleFrames,omitempty"`
}

func (x *ProcessDoubleReplacing_Request) Reset() {
	*x = ProcessDoubleReplacing_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessDoubleReplacing_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDoubleReplacing_Request) ProtoMessage() {}

func (x *ProcessDoubleReplacing_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDoubleReplacing_Request.ProtoReflect.Descriptor instead.
func (*ProcessDoubleReplacing_Request) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ProcessDoubleReplacing_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProcessDoubleReplacing_Request) GetInputs() []*DoubleArray {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ProcessDoubleReplacing_Request) GetSampleFrames() int32 {
	if x != nil {
		return x.SampleFrames
	}
	return 0
}

type ProcessDoubleReplacing_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outputs []*DoubleArray `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (x *ProcessDoubleReplacing_Reply) Reset() {
	*x = ProcessDoubleReplacing_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessDoubleReplacing_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDoubleReplacing_Reply) ProtoMessage() {}

func (x *ProcessDoubleReplacing_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDoubleReplacing_Reply.ProtoReflect.Descriptor instead.
func (*ProcessDoubleReplacing_Reply) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ProcessDoubleReplacing_Reply) GetOutputs() []*DoubleArray {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type GetParameter_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Index int32  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *GetParameter_Request) Reset() {
	*x = GetParameter_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParameter_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameter_Request) ProtoMessage() {}

func (x *GetParameter_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameter_Request.ProtoReflect.Descriptor instead.
func (*GetParameter_Request) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetParameter_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetParameter_Request) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type GetParameter_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetParameter_Reply) Reset() {
	*x = GetParameter_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParameter_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameter_Reply) ProtoMessage() {}

func (x *GetParameter_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameter_Reply.ProtoReflect.Descriptor instead.
func (*GetParameter_Reply) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetParameter_Reply) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetParameter_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Index int32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Value float32 `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetParameter_Request) Reset() {
	*x = SetParameter_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetParameter_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParameter_Request) ProtoMessage() {}

func (x *SetParameter_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParameter_Request.ProtoReflect.Descriptor instead.
func (*SetParameter_Request) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SetParameter_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetParameter_Request) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SetParameter_Request) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetParameter_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetParameter_Reply) Reset() {
	*x = SetParameter_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetParameter_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParameter_Reply) ProtoMessage() {}

func (x *SetParameter_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParameter_Reply.ProtoReflect.Descriptor instead.
func (*SetParameter_Reply) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{4, 1}
}

type Echo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *Echo_Request) Reset() {
	*x = Echo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo_Request) ProtoMessage() {}

func (x *Echo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo_Request.ProtoReflect.Descriptor instead.
func (*Echo_Request) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Echo_Request) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type Echo_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *Echo_Reply) Reset() {
	*x = Echo_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vstbridge_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo_Reply) ProtoMessage() {}

func (x *Echo_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_vstbridge_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo_Reply.ProtoReflect.Descriptor instead.
func (*Echo_Reply) Descriptor() ([]byte, []int) {
	return file_vstbridge_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Echo_Reply) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

var File_vstbridge_proto protoreflect.FileDescriptor

var file_vstbridge_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x22, 0x53, 0x0a, 0x0d,
	0x53, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x1a, 0x39, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0xba, 0x01, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x1a, 0x6c, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2d, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x73, 0x1a, 0x38, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a,
	0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x22, 0xc2,
	0x01, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x1a, 0x6d, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x06, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x30, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x44,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x73, 0x22, 0x5e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x1a, 0x2f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x1a, 0x1d, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x5e, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x1a, 0x45, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x3e, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x1a, 0x1b, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x1a, 0x19, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x73, 0x74, 0x72, 0x22, 0x20, 0x0a, 0x0a, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x0b, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x8c, 0x04, 0x0a, 0x09, 0x56, 0x53, 0x54,
	0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x17,
	0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x53, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74,
	0x65, 0x12, 0x20, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x65,
	0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e,
	0x53, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x2e, 0x76, 0x73, 0x74, 0x62,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x6e, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x2e,
	0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x69, 0x6e, 0x67,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x44, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x30, 0x69, 0x7a, 0x6e, 0x30, 0x69, 0x7a, 0x2f, 0x76,
	0x6d, 0x2d, 0x76, 0x73, 0x74, 0x2d, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x76, 0x73, 0x74, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x3b, 0x76, 0x73, 0x74, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vstbridge_proto_rawDescOnce sync.Once
	file_vstbridge_proto_rawDescData = file_vstbridge_proto_rawDesc
)

func file_vstbridge_proto_rawDescGZIP() []byte {
	file_vstbridge_proto_rawDescOnce.Do(func() {
		file_vstbridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_vstbridge_proto_rawDescData)
	})
	return file_vstbridge_proto_rawDescData
}

var file_vstbridge_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_vstbridge_proto_goTypes = []interface{}{
	(*SetSampleRate)(nil),                  // 0: vstbridge.SetSampleRate
	(*ProcessReplacing)(nil),               // 1: vstbridge.ProcessReplacing
	(*ProcessDoubleReplacing)(nil),         // 2: vstbridge.ProcessDoubleReplacing
	(*GetParameter)(nil),                   // 3: vstbridge.GetParameter
	(*SetParameter)(nil),                   // 4: vstbridge.SetParameter
	(*Echo)(nil),                           // 5: vstbridge.Echo
	(*FloatArray)(nil),                     // 6: vstbridge.FloatArray
	(*DoubleArray)(nil),                    // 7: vstbridge.DoubleArray
	(*SetSampleRate_Request)(nil),          // 8: vstbridge.SetSampleRate.Request
	(*SetSampleRate_Reply)(nil),            // 9: vstbridge.SetSampleRate.Reply
	(*ProcessReplacing_Request)(nil),       // 10: vstbridge.ProcessReplacing.Request
	(*ProcessReplacing_Reply)(nil),         // 11: vstbridge.ProcessReplacing.Reply
	(*ProcessDoubleReplacing_Request)(nil), // 12: vstbridge.ProcessDoubleReplacing.Request
	(*ProcessDoubleReplacing_Reply)(nil),   // 13: vstbridge.ProcessDoubleReplacing.Reply
	(*GetParameter_Request)(nil),           // 14: vstbridge.GetParameter.Request
	(*GetParameter_Reply)(nil),             // 15: vstbridge.GetParameter.Reply
	(*SetParameter_Request)(nil),           // 16: vstbridge.SetParameter.Request
	(*SetParameter_Reply)(nil),             // 17: vstbridge.SetParameter.Reply
	(*Echo_Request)(nil),                   // 18: vstbridge.Echo.Request
	(*Echo_Reply)(nil),                     // 19: vstbridge.Echo.Reply
}
var file_vstbridge_proto_depIdxs = []int32{
	6,  // 0: vstbridge.ProcessReplacing.Request.inputs:type_name -> vstbridge.FloatArray
	6,  // 1: vstbridge.ProcessReplacing.Reply.outputs:type_name -> vstbridge.FloatArray
	7,  // 2: vstbridge.ProcessDoubleReplacing.Request.inputs:type_name -> vstbridge.DoubleArray
	7,  // 3: vstbridge.ProcessDoubleReplacing.Reply.outputs:type_name -> vstbridge.DoubleArray
	18, // 4: vstbridge.VSTBridge.Echo:input_type -> vstbridge.Echo.Request
	8,  // 5: vstbridge.VSTBridge.SetSampleRate:input_type -> vstbridge.SetSampleRate.Request
	10, // 6: vstbridge.VSTBridge.ProcessReplacing:input_type -> vstbridge.ProcessReplacing.Request
	12, // 7: vstbridge.VSTBridge.ProcessDoubleReplacing:input_type -> vstbridge.ProcessDoubleReplacing.Request
	14, // 8: vstbridge.VSTBridge.GetParameter:input_type -> vstbridge.GetParameter.Request
	16, // 9: vstbridge.VSTBridge.SetParameter:input_type -> vstbridge.SetParameter.Request
	19, // 10: vstbridge.VSTBridge.Echo:output_type -> vstbridge.Echo.Reply
	9,  // 11: vstbridge.VSTBridge.SetSampleRate:output_type -> vstbridge.SetSampleRate.Reply
	11, // 12: vstbridge.VSTBridge.ProcessReplacing:output_type -> vstbridge.ProcessReplacing.Reply
	13, // 13: vstbridge.VSTBridge.ProcessDoubleReplacing:output_type -> vstbridge.ProcessDoubleReplacing.Reply
	15, // 14: vstbridge.VSTBridge.GetParameter:output_type -> vstbridge.GetParameter.Reply
	17, // 15: vstbridge.VSTBridge.SetParameter:output_type -> vstbridge.SetParameter.Reply
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_vstbridge_proto_init() }
func file_vstbridge_proto_init() {
	if File_vstbridge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vstbridge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSampleRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessReplacing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessDoubleReplacing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSampleRate_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSampleRate_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessReplacing_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessReplacing_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessDoubleReplacing_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessDoubleReplacing_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParameter_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParameter_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetParameter_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetParameter_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vstbridge_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vstbridge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vstbridge_proto_goTypes,
		DependencyIndexes: file_vstbridge_proto_depIdxs,
		MessageInfos:      file_vstbridge_proto_msgTypes,
	}.Build()
	File_vstbridge_proto = out.File
	file_vstbridge_proto_rawDesc = nil
	file_vstbridge_proto_goTypes = nil
	file_vstbridge_proto_depIdxs = nil
}
